# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from turbine._proto import turbine_pb2 as turbine__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in turbine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TurbineServiceStub(object):
    """TurbineService is the main API for submitting and managing tasks
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/turbine.TurbineService/SubmitTask',
                request_serializer=turbine__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=turbine__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.SubmitBatch = channel.unary_unary(
                '/turbine.TurbineService/SubmitBatch',
                request_serializer=turbine__pb2.SubmitBatchRequest.SerializeToString,
                response_deserializer=turbine__pb2.SubmitBatchResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/turbine.TurbineService/GetTaskStatus',
                request_serializer=turbine__pb2.GetTaskStatusRequest.SerializeToString,
                response_deserializer=turbine__pb2.GetTaskStatusResponse.FromString,
                _registered_method=True)
        self.GetTaskResult = channel.unary_unary(
                '/turbine.TurbineService/GetTaskResult',
                request_serializer=turbine__pb2.GetTaskResultRequest.SerializeToString,
                response_deserializer=turbine__pb2.GetTaskResultResponse.FromString,
                _registered_method=True)
        self.WaitForResult = channel.unary_unary(
                '/turbine.TurbineService/WaitForResult',
                request_serializer=turbine__pb2.WaitForResultRequest.SerializeToString,
                response_deserializer=turbine__pb2.WaitForResultResponse.FromString,
                _registered_method=True)
        self.RevokeTask = channel.unary_unary(
                '/turbine.TurbineService/RevokeTask',
                request_serializer=turbine__pb2.RevokeTaskRequest.SerializeToString,
                response_deserializer=turbine__pb2.RevokeTaskResponse.FromString,
                _registered_method=True)
        self.RetryTask = channel.unary_unary(
                '/turbine.TurbineService/RetryTask',
                request_serializer=turbine__pb2.RetryTaskRequest.SerializeToString,
                response_deserializer=turbine__pb2.RetryTaskResponse.FromString,
                _registered_method=True)
        self.GetQueueInfo = channel.unary_unary(
                '/turbine.TurbineService/GetQueueInfo',
                request_serializer=turbine__pb2.GetQueueInfoRequest.SerializeToString,
                response_deserializer=turbine__pb2.GetQueueInfoResponse.FromString,
                _registered_method=True)
        self.PurgeQueue = channel.unary_unary(
                '/turbine.TurbineService/PurgeQueue',
                request_serializer=turbine__pb2.PurgeQueueRequest.SerializeToString,
                response_deserializer=turbine__pb2.PurgeQueueResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/turbine.TurbineService/SubscribeEvents',
                request_serializer=turbine__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=turbine__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/turbine.TurbineService/HealthCheck',
                request_serializer=turbine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=turbine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TurbineServiceServicer(object):
    """TurbineService is the main API for submitting and managing tasks
    """

    def SubmitTask(self, request, context):
        """Submit a new task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBatch(self, request, context):
        """Submit multiple tasks in batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Get task status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskResult(self, request, context):
        """Get task result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForResult(self, request, context):
        """Wait for task result (long polling)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeTask(self, request, context):
        """Revoke/cancel a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryTask(self, request, context):
        """Retry a failed task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueInfo(self, request, context):
        """Get queue information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeQueue(self, request, context):
        """Purge a queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Subscribe to task events (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TurbineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=turbine__pb2.SubmitTaskRequest.FromString,
                    response_serializer=turbine__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'SubmitBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBatch,
                    request_deserializer=turbine__pb2.SubmitBatchRequest.FromString,
                    response_serializer=turbine__pb2.SubmitBatchResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=turbine__pb2.GetTaskStatusRequest.FromString,
                    response_serializer=turbine__pb2.GetTaskStatusResponse.SerializeToString,
            ),
            'GetTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskResult,
                    request_deserializer=turbine__pb2.GetTaskResultRequest.FromString,
                    response_serializer=turbine__pb2.GetTaskResultResponse.SerializeToString,
            ),
            'WaitForResult': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitForResult,
                    request_deserializer=turbine__pb2.WaitForResultRequest.FromString,
                    response_serializer=turbine__pb2.WaitForResultResponse.SerializeToString,
            ),
            'RevokeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeTask,
                    request_deserializer=turbine__pb2.RevokeTaskRequest.FromString,
                    response_serializer=turbine__pb2.RevokeTaskResponse.SerializeToString,
            ),
            'RetryTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryTask,
                    request_deserializer=turbine__pb2.RetryTaskRequest.FromString,
                    response_serializer=turbine__pb2.RetryTaskResponse.SerializeToString,
            ),
            'GetQueueInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueInfo,
                    request_deserializer=turbine__pb2.GetQueueInfoRequest.FromString,
                    response_serializer=turbine__pb2.GetQueueInfoResponse.SerializeToString,
            ),
            'PurgeQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeQueue,
                    request_deserializer=turbine__pb2.PurgeQueueRequest.FromString,
                    response_serializer=turbine__pb2.PurgeQueueResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=turbine__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=turbine__pb2.TaskEvent.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=turbine__pb2.HealthCheckRequest.FromString,
                    response_serializer=turbine__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'turbine.TurbineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('turbine.TurbineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TurbineService(object):
    """TurbineService is the main API for submitting and managing tasks
    """

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/SubmitTask',
            turbine__pb2.SubmitTaskRequest.SerializeToString,
            turbine__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/SubmitBatch',
            turbine__pb2.SubmitBatchRequest.SerializeToString,
            turbine__pb2.SubmitBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/GetTaskStatus',
            turbine__pb2.GetTaskStatusRequest.SerializeToString,
            turbine__pb2.GetTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/GetTaskResult',
            turbine__pb2.GetTaskResultRequest.SerializeToString,
            turbine__pb2.GetTaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/WaitForResult',
            turbine__pb2.WaitForResultRequest.SerializeToString,
            turbine__pb2.WaitForResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/RevokeTask',
            turbine__pb2.RevokeTaskRequest.SerializeToString,
            turbine__pb2.RevokeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/RetryTask',
            turbine__pb2.RetryTaskRequest.SerializeToString,
            turbine__pb2.RetryTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/GetQueueInfo',
            turbine__pb2.GetQueueInfoRequest.SerializeToString,
            turbine__pb2.GetQueueInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/PurgeQueue',
            turbine__pb2.PurgeQueueRequest.SerializeToString,
            turbine__pb2.PurgeQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/turbine.TurbineService/SubscribeEvents',
            turbine__pb2.SubscribeEventsRequest.SerializeToString,
            turbine__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.TurbineService/HealthCheck',
            turbine__pb2.HealthCheckRequest.SerializeToString,
            turbine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkflowServiceStub(object):
    """WorkflowService handles workflow operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitChain = channel.unary_unary(
                '/turbine.WorkflowService/SubmitChain',
                request_serializer=turbine__pb2.SubmitChainRequest.SerializeToString,
                response_deserializer=turbine__pb2.SubmitWorkflowResponse.FromString,
                _registered_method=True)
        self.SubmitGroup = channel.unary_unary(
                '/turbine.WorkflowService/SubmitGroup',
                request_serializer=turbine__pb2.SubmitGroupRequest.SerializeToString,
                response_deserializer=turbine__pb2.SubmitWorkflowResponse.FromString,
                _registered_method=True)
        self.SubmitChord = channel.unary_unary(
                '/turbine.WorkflowService/SubmitChord',
                request_serializer=turbine__pb2.SubmitChordRequest.SerializeToString,
                response_deserializer=turbine__pb2.SubmitWorkflowResponse.FromString,
                _registered_method=True)
        self.GetWorkflowStatus = channel.unary_unary(
                '/turbine.WorkflowService/GetWorkflowStatus',
                request_serializer=turbine__pb2.GetWorkflowStatusRequest.SerializeToString,
                response_deserializer=turbine__pb2.GetWorkflowStatusResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer(object):
    """WorkflowService handles workflow operations
    """

    def SubmitChain(self, request, context):
        """Submit a chain of tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitGroup(self, request, context):
        """Submit a group of parallel tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitChord(self, request, context):
        """Submit a chord (group + callback)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowStatus(self, request, context):
        """Get workflow status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitChain': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitChain,
                    request_deserializer=turbine__pb2.SubmitChainRequest.FromString,
                    response_serializer=turbine__pb2.SubmitWorkflowResponse.SerializeToString,
            ),
            'SubmitGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGroup,
                    request_deserializer=turbine__pb2.SubmitGroupRequest.FromString,
                    response_serializer=turbine__pb2.SubmitWorkflowResponse.SerializeToString,
            ),
            'SubmitChord': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitChord,
                    request_deserializer=turbine__pb2.SubmitChordRequest.FromString,
                    response_serializer=turbine__pb2.SubmitWorkflowResponse.SerializeToString,
            ),
            'GetWorkflowStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowStatus,
                    request_deserializer=turbine__pb2.GetWorkflowStatusRequest.FromString,
                    response_serializer=turbine__pb2.GetWorkflowStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'turbine.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('turbine.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService(object):
    """WorkflowService handles workflow operations
    """

    @staticmethod
    def SubmitChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.WorkflowService/SubmitChain',
            turbine__pb2.SubmitChainRequest.SerializeToString,
            turbine__pb2.SubmitWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.WorkflowService/SubmitGroup',
            turbine__pb2.SubmitGroupRequest.SerializeToString,
            turbine__pb2.SubmitWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitChord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.WorkflowService/SubmitChord',
            turbine__pb2.SubmitChordRequest.SerializeToString,
            turbine__pb2.SubmitWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbine.WorkflowService/GetWorkflowStatus',
            turbine__pb2.GetWorkflowStatusRequest.SerializeToString,
            turbine__pb2.GetWorkflowStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
